#%RAML 0.8
---
title: crowdsourcing-mart-api
baseUri: http://localhost:8000

/api/account:
        /register:
                post:
                    description: |
                            创建用户
                    body:
                        application/json:
                            schema: |
                                {
                                    "type":"object",
                                    "required": true,
                                    "properties":{
                                        "username":{
                                                "type":"string",
                                                "required": true
                                        },

                                        "name":{
                                                "type":"string",
                                                "required":true
                                        },
                                        "password":{
                                                "type":"string",
                                                "required":true
                                        },
                                        "mobile":{
                                                "type":"string",
                                                "required":true
                                        },
                                        "create_time":{
                                                "type":"timestamp",
                                                "required":true
                                        },
                                        "update_time":{
                                                "type":"timestamp",
                                                "required":true
                                        },
                                        "email":{
                                                "type":"string",
                                                "required":true
                                        },
                                        "ext_params":{
                                                "type":"json",
                                                "required":false
                                        }

                                    }
                                }

                            example: |
                                {
                                          "username":"shikun666",
                                          "name":"shikun",
                                          "password": "1992114sk",
                                          "mobile":"18817369206",
                                          "create_time":"",
                                          "update_time":"",
                                          "email":"18817369206@163.com",
                                          "ext_params":{
                                                            "test":"111",
                                          				    "fav":"sdfsd"
                                                        }
                                }
                    responses:
                        200:
                           body:
                                application/json:
                                   example: |
                                         {
                                           "status": "200",
                                           "result": 1
                                         }


        /login:
             post:
                description: |
                    用户登录
                body:
                    application/json:
                        schema: |
                                            {
                                                "type":"object",
                                                "required": true,
                                                "properties":{
                                                    "username":{
                                                            "type":"string",
                                                            "required": true
                                                    },
                                                    "password":{
                                                            "type":"string",
                                                            "required":true
                                                    }

                                                }
                                            }

                        example: |
                                            {
                                                      "username":"shikun666",
                                                      "password": "1992114sk"
                responses:
                        200:
                            body:
                                application/json:
                                          example: |

                                               {
                                                 "status": "200",
                                                 "result": "7224074aa44245d09cf2a346c00ef4a7"
                                               }

/api/project:
        /add:
            post:
                    description: |
                            创建众包项目
                    body:
                        application/json:
                            schema: |
                                {
                                    "type":"object",
                                    "required": true,
                                    "properties":{
                                        "cost":{
                                                "type":"string",
                                                "required": true
                                        },

                                        "delivery_cycle":{
                                                "type":"int",
                                                "required":true
                                        },
                                        "warranty_cycle":{
                                                "type":"int",
                                                "required":true
                                        },
                                        "address":{
                                                "type":"string",
                                                "required":true
                                        },
                                        "description":{
                                                "type":"string",
                                                "required":true
                                        },
                                        "project_type":{
                                                "type":"string",
                                                "required":true
                                        },
                                        "project_user_name":{
                                                "type":"string",
                                                "required":true
                                        },
                                        "create_date":{
                                                "type":"string",
                                                "required":true
                                        }
                                    }
                                }

                            example: |
                                {
                                       "cost":"1000",
                                       "delivery_cycle": "20",
                                       "warranty_cycle":"10",
                                       "address":"shanghai",
                                       "description":"a test project",
                                       "project_type":"IOS",
                                       "project_user_name":"shikun",
                                       "create_date":"2016-10-13 07:45:57"

                                }
                    responses:
                             200:
                                body:
                                   application/json:
                                            example: |

                                                    {
                                                      "status": "200",
                                                      "result": 1
                                                    }
        /list:
            get:
                    description: |
                            众包项目列表接口
                    responses:
                             200:
                                body:
                                   application/json:
                                            example: |

                                                    {
                                                      "status": "200",
                                                      "result": [
                                                        {
                                                          "id": 1,
                                                          "cost": 1000,
                                                          "delivery_cycle": 30,
                                                          "warranty_cycle": 30,
                                                          "create_date": null,
                                                          "address": "shanghai",
                                                          "description": "first project",
                                                          "project_user_name": "shikun",
                                                          "file": null,
                                                          "project_type": null,
                                                          "username": null
                                                        },
                                                        {
                                                          "id": 2,
                                                          "cost": 1000,
                                                          "delivery_cycle": 30,
                                                          "warranty_cycle": 30,
                                                          "create_date": null,
                                                          "address": "shanghai",
                                                          "description": "second project",
                                                          "project_user_name": "shikun",
                                                          "file": null,
                                                          "project_type": null,
                                                          "username": "yinkanglin"
                                                        },
                                                        {
                                                          "id": 3,
                                                          "cost": 10000,
                                                          "delivery_cycle": 30,
                                                          "warranty_cycle": 30,
                                                          "create_date": null,
                                                          "address": "shanghai",
                                                          "description": "third project",
                                                          "project_user_name": "shikun",
                                                          "file": null,
                                                          "project_type": "Andriod",
                                                          "username": null
                                                        },
                                                        {
                                                          "id": 4,
                                                          "cost": 100000,
                                                          "delivery_cycle": 120,
                                                          "warranty_cycle": 120,
                                                          "create_date": null,
                                                          "address": "shanghai",
                                                          "description": "crowd sourcing",
                                                          "project_user_name": "qiujuan",
                                                          "file": null,
                                                          "project_type": "Web",
                                                          "username": null
                                                        },

                                                      }







